---
name: Rust tests

on:
  pull_request:
  push:

jobs:
  rust_tests:
    name: Rust tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Check code format with rustfmt
        uses: actions-rust-lang/rustfmt@v1
