---
name: Rust tests

env:
  RUSTFLAGS: "-Dwarnings"

on:
  pull_request:
  push:

jobs:
  rust_tests:
    name: Rust tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install required packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler
          version: 1.0
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rust smart caching
        uses: Swatinem/rust-cache@v2
      - name: Check code format with rustfmt
        uses: actions-rust-lang/rustfmt@v1
      - name: Run cargo clippy
        run: cargo clippy --all-features --all-targets --no-deps -- -Dclippy::nursery -Dclippy::pedantic
      - name: Run Rust tests
        run: cargo test
